--Write queries to create the new tables in your database based on the ERD provided in the project folder.
CREATE TABLE authors (
    author_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_name varchar(255),
    nationality varchar(255)
);