--Write queries to create the new tables in your database based on the ERD provided in the project folder.
CREATE TABLE IF NOT EXISTS books (
    book_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255),
    publication_year INTEGER,
    in_stock BOOLEAN DEFAULT true,
    author_id INTEGER REFERENCES authors(author_id) 
);