--Write queries to create the new tables in your database based on the ERD provided in the project folder.
CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    genre_name VARCHAR(100)
);